---
title: "Logistic Regression Figures"
author: "David Knorr"
date: "March 2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}


library(pacman)
p_load(tidyverse, caret, spdep, rgdal, rgeos, factoextra, tigris, randomForest, pROC, plotROC, knitr, kableExtra, data.table)

Dependent <- readRDS("DependentVariable.rds")
Lagged <- readRDS("lagged2000Variables.rds")
PredictiveVars2000 <- readRDS("PredictiveVars1990_2000.rds") %>% dplyr::select(-contains("90"), - contains("welfare"), -contains("kids"))

knitr::knit_hooks$set(inline = function(x) { if(!is.numeric(x)){ x }else{ prettyNum(round(x,2), big.mark=",") } })

knitr::opts_chunk$set(fig.width=12, fig.height=7) 
options(knitr.table.format = "latex")
```

## Logistic Regression


```{r cars, echo=FALSE, warning=FALSE}

OrigVs <- c(names(PredictiveVars2000))
PrettyNamedVs <- c("CENSUSTRACTID", "PCTRENTER", "PCTVACANT", "PCTNONFAM", "UNDER18", "OVER65", "PCTPOV", "PCTUNEMPLOY", "PCTNOCAR", "PCT3CAR", "PCTPUBTRANSP", "PCT20MINCOMMUTE", "PCTBLUECOLLAR",  "PCTBIGUNIT", "PCTRENTBURDEN", "PARKCOVERAGE", "DOWNTOWNDISTANCE", "TRANSITCOVERAGE", "EVICTIONRATE")
VarSwap <- data.frame(OrigVs, PrettyNamedVs) %>% mutate(joinid = gsub("_", "", OrigVs)) %>% filter(OrigVs != "CensusTractID")
Variables <- c("PCTRENTER", "PCTVACANT", "PCTNONFAM", "UNDER18", "OVER65", "PCTPOV", "PCTUNEMPLOY", "PCTNOCAR", "PCT3CAR", "PCTPUBTRANSP", "PCT20MINCOMMUTE", "PCTBLUECOLLAR", "PCTBIGUNIT", "PCTRENTBURDEN", "PARKCOVERAGE", "DOWNTOWNDISTANCE", "TRANSITCOVERAGE", "EVICTIONRATE")

VarsX <- c("BoolGentX", "PCTRENTER", "PCTVACANT", "PCTNONFAM", "UNDER18", "OVER65", "PCTPOV", "PCTUNEMPLOY", "PCTNOCAR", "PCT3CAR", "PCTPUBTRANSP", "PCT20MINCOMMUTE", "PCTBLUECOLLAR", "PCTBIGUNIT", "PCTRENTBURDEN", "PARKCOVERAGE", "DOWNTOWNDISTANCE", "TRANSITCOVERAGE", "EVICTIONRATE")

LogReg_df <- inner_join(Dependent, PredictiveVars2000) 

prePCA <- LogReg_df %>% dplyr::select(-CensusTractID, -BoolGent)
names(prePCA) <- VarsX
# names(prePCA) <- Variables
# prePCAnamed <- LogReg_df %>% dplyr::select(CensusTractID, contains("Bool"))
# 
# PCA <- prcomp(prePCA, scale. = TRUE) 
# Biplot <- fviz_pca_var(PCA, repel = TRUE, col.var = "contrib",
#              gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), title = "PCA Biplot")
# Biplot
```
\pagebreak



\pagebreak
```{r dk3, echo=FALSE, warning=FALSE}
# PostPCA<- data.frame(PCA$x) %>% dplyr::select(PC1, PC2, PC3, PC4, PC5) %>% cbind(prePCAnamed) 
# 
# trainingindexes <- createDataPartition(PostPCA$BoolGent, p = .6, list = FALSE)
# 
# train <- PostPCA[trainingindexes,]
# test <- PostPCA[-trainingindexes,]

set.seed(11)

#######
trainingindexes <- createDataPartition(prePCA$BoolGentX, p = .7, list = FALSE)

train <- prePCA[trainingindexes,]
test <- prePCA[-trainingindexes,]


tc <- trainControl(method = "LOOCV",classProbs = TRUE, summaryFunction = twoClassSummary, savePredictions = TRUE, preProcOptions = list(pcaComp = 5))

lreg<-train(BoolGentX~ ., data=train, method="glm",family=binomial(),
             metric = "ROC", preProcess = "pca", trControl= tc)

predictions <- predict(lreg, test, type = "prob") %>% cbind(test$BoolGentX)

predictions$BoolGent <- as.factor(ifelse(test$BoolGentX == "X0", 0, 1))
test$BoolGent <- as.factor(ifelse(test$BoolGentX == "X0", 0, 1))

optimthresh <- SDMTools::optim.thresh(test$BoolGent, predictions$X0)
FinalPred <- predictions %>% mutate(ModelPred = as.factor(ifelse(X0 <= optimthresh$`sensitivity=specificity`[1], 1, 0)))


##PCA for figures on all training data
trainPCA <- train %>% dplyr::select(-BoolGentX)
names(trainPCA) <- Variables
prePCAnamed <- LogReg_df %>% dplyr::select(CensusTractID, contains("Bool"))

PCA <- prcomp(trainPCA, scale. = TRUE) 
Biplot <- fviz_pca_var(PCA, repel = TRUE, col.var = "contrib",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), title = "PCA Biplot")
Biplot

#Reporting Tables
cf_matrix <- confusionMatrix(FinalPred$ModelPred,FinalPred$BoolGent)
cf_table <- cf_matrix$table

dat <- matrix(cf_table, nrow=2, ncol=2, 
              dimnames=list(c("Not Gentrifying", "Gentrifying"), c("Not Gentrifying", "Gentrifying")))

# now set the names *of the dimensions* (not the row/colnames)
names(dimnames(dat)) <- c("Predicted", "Observed")


CFtable <- kable(dat,"latex", longtable = TRUE , booktabs = T, escape = F, caption = "Confusion Matrix", format.args = list(big.mark = ",")) %>% kable_styling(position = "center",font_size = 11, latex_options = c("hold_position", "repeat_header")) %>% add_header_above(c("Predicted" = 1, "Observed" = 2))
print(CFtable)
##Model Performance Table 
metrics <- cf_matrix$overall
class <- as.data.frame(cf_matrix$byClass)
names(class) <- "value"

perf_table <- kable(class,"latex", longtable = TRUE , booktabs = T, escape = F,linesep = "", digits= 3, caption = "Model Performance Metrics", format.args = list(big.mark = ",")) %>% kable_styling(position = "center",font_size = 11, latex_options = c("hold_position", "repeat_header"))

print(perf_table)
#cf_matrix
RotationPlot <- as.data.frame(PCA$rotation) %>% cbind(Variables) %>% dplyr::select(Variables, PC1, PC2, PC3, PC4, PC5)

#df <- cbind(Variable = rownames(RotationPlot), RotationPlot)
#rownames(df) <- 1:nrow(df)
df_rot <- RotationPlot %>% mutate_at(2:6, round, 3)

#df$Variable1 <- gsub("_", "", df$Variable)

DF1 <- df_rot %>% mutate_if(is.numeric, function(x) {
    cell_spec(x, "latex", bold = abs(x) > .2, 
              color = ifelse(x < 0, "red"," black"))})

DF_2 <- DF1 %>% dplyr::select(Variables, PC1, PC2, PC3, PC4, PC5)

kable(DF_2,"latex", longtable = TRUE , align = "lccccc", booktabs = T, digits =2, escape = F, caption = "PCA Rotation Values") %>% kable_styling(position = "center",font_size = 8, latex_options = c("hold_position", "repeat_header"))




####Summary Stats- ROC Curve
df <- data.frame(predictor = predictions$X0,
                       known.truth = FinalPred$`test$BoolGent`,
                       model = "train")

p_train <- predict(lreg, train[-1],type = "prob")
p_test <- predict(lreg, test[c(-1, -20)], type = "prob")
p_testVec <- c(p_test$X1)
p_trainVec <- c(p_train$X1)

df_dk2 <- rbind(data.frame(predictor = p_train[,2],
                       known.truth = train$BoolGentX,
                       Model = "Train"),
            data.frame(predictor = p_test[,2],
                       known.truth = test$BoolGent,
                       Model = "Test"))

df_dk2 <- df_dk2 %>% mutate(rnd = round(predictor, 3))

k2 <- ggplot(df_dk2, aes(d = known.truth, m = rnd, color = Model)) + 
  geom_roc(n.cuts = 6)+
  coord_equal() +
  style_roc() + labs(title = "ROC Plot")

k2

testroc <- data.frame(predictor = p_test[,2],
                       known.truth = test$BoolGentX,
                       Model = "Test")

ggplot(testroc, aes(d = predictor, m = known.truth)) + geom_roc()


roc_obj_test <- roc(test$BoolGentX, p_testVec)
auc(roc_obj_test)
roc_obj_train <- roc(train$BoolGentX, p_trainVec)
auc(roc_obj_train)

ModelSummary <- summary(lreg)
ModelSummaryTable <- ModelSummary$coefficients

summarystats <-  data.frame(cf_matrix$overall)
summarystats2 <- data.frame(cf_matrix$byClass)

sumtab2 <- setDT(summarystats2, keep.rownames = TRUE)[]
names(sumtab2) <- c("Metric", "Value")
sumtab <- setDT(summarystats, keep.rownames = TRUE)[]
names(sumtab) <- c("Metric", "Value")
allsumstats <- rbind(sumtab, sumtab2, fill = TRUE)
stat <- c("Accuracy","Balanced Accuracy", "Sensitivity", "Specificity", "Kappa", "AccuracyLower", "AccuracyUpper", "Precision", "Recall", "F1")


#test_set <- RFmodel_preds %>% mutate(pred = as.factor(paste0("X", FinalPred))) %>% select(pred, obs = `test$BoolGentX`, X0, X1)
selectstats <- allsumstats %>% filter(Metric %in% stat) 

kable(selectstats,"latex", longtable = TRUE , booktabs = T, escape = F, digits = 3, caption = "Random Forest Model Performance", format.args = list(big.mark = ",")) %>% kable_styling(position = "center",font_size = 11, latex_options = c("hold_position", "repeat_header")) 


```

```{r dk, echo=FALSE, warning=FALSE}
screeplot <- fviz_eig(PCA, addlabels = TRUE, main = "PCA- Logistic Regression Scree Plot", xlab = "Principle Components")
summary(PCA)
screeplot
```


\pagebreak



```{r df, echo=FALSE, warning=FALSE}

kable(ModelSummaryTable,"latex", longtable = TRUE ,linesep = "", align = "c", digits = c(3, 2, 2, 4), booktabs = T, escape = F, caption = "Logistic Classification Model Parameters", format.args = list(big.mark = ",")) %>% kable_styling(position = "center",font_size = 8, latex_options = c("hold_position", "repeat_header"))

```

```{r predictions, echo= FALSE, eval = FALSE}
data2016 <- readRDS("x2016Data.rds") %>% dplyr::select(-year, -MedRent, -MedIncome, -MedianAgeBuilt, - CollegePct, -PctNonWhite, -Pct_MultiUnit, CensusTractID) %>% filter(complete.cases(.))

IDs2016 <- data2016 %>% dplyr::select(CensusTractID) %>% filter(complete.cases(.))

Ordered16 <- data2016 %>% dplyr::select(Pct_Renters, Pct_Vacant, NonFamPct, Under18, Over65x, PovertyPct, UnemploymentPct, NoCarPct, Pct3Vehicles, PctPubCommute, PctCommuteless20min, PctBlueCollar, PctBigUnits, RentBurdenPct, Park_PctCoverage16, Dist2Downtown, Transit_PctCoverage, EvictionRate)

names(Ordered16) <- names(train[2:19])
project2016PCA <- predict(PCA, Ordered16) 
PC2016 <- as.data.frame(project2016PCA) %>% select(PC1, PC2, PC3, PC4, PC5)
Predictions16 <- predict(lreg, Ordered16, type = "prob") 


Pred16_df <- as.data.frame(Predictions16) %>% cbind(IDs2016)


Davidson <- tracts("TN", "Davidson")

Davidson@data$JOINID = as.character(Davidson@data$GEOID)
sp_jn1 <- geo_join(spatial_data = Davidson, data_frame = Pred16_df, by_sp = "JOINID", by_df = "CensusTractID", how = "inner")
writeOGR(obj=sp_jn1, dsn="C://School//Research//Predictive Variables//Master//FinalPredictions", layer="PredictionProbs", driver="ESRI Shapefile")

Davidson_SF <- st_as_sf(sp_jn1)

colors <- c("seagreen", "cornflowerblue","darkgoldenrod4","tomato", "purple")
cols <- c("seagreen", "cornflowerblue","darkgoldenrod4","tomato", "purple")

ggplot(Davidson_SF) + geom_sf(aes(fill = X1)) + scale_fill_gradient(low = "blue", high = "red") + coord_sf() + theme(legend.position="none")  + theme(legend.position = "right")  + theme(axis.text = element_blank(), axis.ticks = element_blank()) + labs(title = "Nashville Neighborhood Change Predictions", caption = "Geometries: tigris")

```

